name: build-test-publish
on:
  workflow_dispatch:
    inputs:
      versioning_version:
        description: "Manually specify a version. Main requires semver. Free form for other branches."
        required: false
        type: string
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]
  release:
    types:
      - published

jobs:
  build-test-publish:
    uses: bmc-anvil/.github/.github/workflows/orchestrator_flow.yml@main
    secrets:
      PACKAGES_USER: ${{ secrets.PACKAGES_USER }}
      PACKAGES_TOKEN_RW: ${{ secrets.PACKAGES_TOKEN_RW }}
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      packages: write
      security-events: write
    with:
      build_tool: 'maven'
      build_type: 'artifact'
      deploy_package: true
      java_vendor: 'oracle'
      language: 'java'
      language_version: '25'
      services_docker_in_docker: false
      static_analysis_checkstyle_skip: false
      static_analysis_checkstyle_fail_on_violations: false
      testing_options_skip: false
      versioning_version: ${{ github.event.inputs.versioning_version }}
      workflow_dry_run: false
